from __future__ import annotations

import unittest

from novel_flow.prompting.templates import PromptLibrary


class PromptRenderingTests(unittest.TestCase):
    def setUp(self) -> None:
        self.library = PromptLibrary()
        self.common = {
            "research_query": "test query",
            "planning_context_json": "{}",
            "reference_pack": "none",
            "assistant_persona_prompt": "persona",
            "volume_titles_json": '["Volume 1"]',
            "story_spine_json": "{}",
            "worldbuilding_json": "{}",
            "character_bible_json": "{}",
            "event_timeline_json": "[]",
            "character_milestones_json": "[]",
            "twist_designs_json": "[]",
            "previous_chapter_briefs_json": "[]",
            "batch_window_json": '{"start_index":0,"end_index":0,"batch_size":1,"total_chapters":1,"chapter_ids":["ch_001"]}',
            "target_chapter_count": 1,
            "completed_chapter_memory_text": "none",
            "chapter_payload_text": "payload",
            "relevant_world_rules_text": "rules",
            "style_card_text": "style",
            "chapter_brief_json": "{}",
            "step_8_chapter_brief_text": "step8 brief",
            "selection_summary_text": "selection",
            "time_anchor_text": "time anchor",
            "timeline_anchor_facts_text": "timeline facts",
            "chapter_visible_context_text": "visible context",
            "step_1_story_foundation_text": "step1",
            "step_2_worldbuilding_text": "step2",
            "step_3_character_packets_text": "step3",
            "step_4_event_timeline_text": "step4",
            "step_7_story_lines_text": "step7",
            "scene_character_context_text": "characters",
            "relationship_state_text": "relationships",
            "chapter_character_mindsets_text": "mindsets",
            "block_card_text": "block card",
            "prior_block_summary_text": "prior blocks",
            "prior_chapter_text_tail": "chapter tail",
            "current_chapter_written_blocks_json": "[]",
            "human_reaction_target": "[]",
            "cost_shift": "cost shift",
            "reader_feeling_target": "reader feeling",
            "paragraph_budget": "建议 2~5 个自然段；单段尽量 30~120 中文字；超过 180 中文字视为过长",
            "micro_hook": "micro hook",
            "turn_type": "pressure_rise",
            "paragraph_shape": "[]",
            "character_anchor_line": "{}",
            "style_risk_guard": "[]",
            "clue_reveal_mechanism": "",
            "character_reentry_mode": "",
            "target_word_count_text": "2500-3200 words",
            "loaded_skill_instructions_text": "skills",
            "block_revision_plan_json": "{}",
            "review_scope_text": "Review the whole chapter.",
            "output_format_rules": "[]",
            "loaded_tool_context": "tool context",
            "scene_card_text": "scene",
            "previous_scene_tail": "prev",
            "current_chapter_draft_tail": "tail",
            "draft_text": "draft",
            "chapter_text": "chapter",
            "final_polished_text": "final chapter",
            "original_text": "original",
            "rewrite_guidance": "guidance",
            "active_twists_json": "[]",
            "story_lines_json": "[]",
            "dynamic_instruction_text": "{}",
            "revision_plan_json": "{}",
            "schema_name": "schema",
            "bad_json": '{"x": 1}',
            "scene_or_chapter_text": "text",
            "scope": "premise",
            "target_id": "ch_001",
            "guidance": "tighten the logic",
            "book_json": "{}",
            "block_id": "ch_001.sc_001.b001",
            "block_purpose": "pressure beat",
            "block_text": "old block",
            "chapter_json": "{}",
            "premise_json": "{}",
            "characters_json": "[]",
            "story_blueprint_json": "{}",
            "previous_chapter_json": "{}",
            "current_chapter_json": "{}",
            "chapter_id": "ch_001",
            "chapter_title": "Chapter One",
            "chapter_summary": "Summary",
            "chapter_plan_json": "{\"blocks\":[]}",
            "planned_blocks_json": "{\"blocks\":[]}",
            "current_character_mindset_json": "{}",
            "character_card_json": "{}",
            "step_5_scoped_text": "scoped step5",
            "step_6_scoped_text": "scoped step6",
            "step_1_to_7_outputs_json": "{}",
            "previous_chapter_full_text": "",
            "completed_chapter_summary_bundle": "none",
            "writing_requirements_json": "{}",
            "chapter_context_json": "{}",
            "blueprint_json": "{}",
            "review_json": "{}",
            "review_reports_json": "{}",
            "chapter_summary_context_text": "chapter summary context",
            "patch_target_json": "{}",
            "global_constraints_json": "[]",
            "current_block_card_text": "current block card",
            "current_block_text": "current block text",
            "previous_block_text": "previous block text",
            "next_block_text": "next block text",
            "patch_plan_json": "{}",
            "patched_block_contexts_json": "[]",
            "minimal_context_text": "minimal patch context",
            "merged_chapter_text": "merged chapter text",
        }

    def test_new_prompts_render_without_format_errors(self) -> None:
        prompt_paths = [
            "writer/step_6_twist_designs.txt",
            "writer/step_7_story_lines.txt",
            "writer/step_8_chapter_briefs.txt",
            "writer/build_character_mindset.txt",
            "writer/plan_content_blocks.txt",
            "writer/write_chapter_full.txt",
            "writer/draft_content_block.txt",
            "writer/review_block_quality.txt",
            "writer/revise_content_block.txt",
            "writer/make_scene_plan.txt",
            "writer/write_scene_draft.txt",
            "writer/polish_scene.txt",
            "writer/chapter_final_polish.txt",
            "writer/format_adjustment_suggestion.txt",
            "writer/rewrite_scene.txt",
            "writer/summarize_actual_chapter.txt",
            "writer/review_instruction_compliance.txt",
            "writer/review_character_integrity.txt",
            "writer/review_time_consistency.txt",
            "writer/review_reveal_leak.txt",
            "writer/review_prose_quality.txt",
            "writer/review_plot_logic.txt",
            "writer/review_continuity.txt",
            "writer/review_humanity.txt",
            "writer/review_structure_and_continuity.txt",
            "writer/review_prose_and_humanity.txt",
            "writer/build_chapter_patch_plan.txt",
            "writer/rewrite_blocks_by_plan.txt",
            "writer/judge_patched_chapter.txt",
            "writer/review_chapter_engine.txt",
            "writer/repair_json.txt",
            "writer/revise_concept.txt",
            "writer/rewrite_unit.txt",
            "writer/rewrite_chapter.txt",
            "writer/revise_blueprint.txt",
            "critic/check_reveal_leak.txt",
            "critic/check_plot_logic.txt",
            "critic/check_clue_origin.txt",
            "critic/check_prose_quality.txt",
            "critic/check_chapter_engine.txt",
            "critic/review.txt",
        ]
        for path in prompt_paths:
            rendered = self.library.render(path, **self.common)
            self.assertIsInstance(rendered, str, path)
            self.assertTrue(rendered.strip(), path)


if __name__ == "__main__":
    unittest.main()
